/**
 * Auto-generated RKLLM constants and function registry
 * Generated from comprehensive rkllm.h header parsing
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 */

#include "rkllm_auto_generated.h"
#include <stdlib.h>
#include <string.h>

// Comprehensive constants function
int rkllm_get_constants_auto(char** result_json) {
    if (!result_json) return -1;
    
    json_object* constants = json_object_new_object();
    
    // CPU Masks and Constants from #define
    json_object* cpu_masks = json_object_new_object();
    json_object* other_defines = json_object_new_object();
    json_object_object_add(cpu_masks, "CPU0", json_object_new_int(1));
    json_object_object_add(cpu_masks, "CPU1", json_object_new_int(2));
    json_object_object_add(cpu_masks, "CPU2", json_object_new_int(4));
    json_object_object_add(cpu_masks, "CPU3", json_object_new_int(8));
    json_object_object_add(cpu_masks, "CPU4", json_object_new_int(16));
    json_object_object_add(cpu_masks, "CPU5", json_object_new_int(32));
    json_object_object_add(cpu_masks, "CPU6", json_object_new_int(64));
    json_object_object_add(cpu_masks, "CPU7", json_object_new_int(128));
    json_object_object_add(constants, "CPU_MASKS", cpu_masks);
    json_object_object_add(constants, "OTHER_DEFINES", other_defines);

    // LLMCallState enum
    json_object* llm_call_states = json_object_new_object();
    json_object_object_add(llm_call_states, "RKLLM_RUN_NORMAL", json_object_new_int(0));
    json_object_object_add(llm_call_states, "RKLLM_RUN_WAITING", json_object_new_int(1));
    json_object_object_add(llm_call_states, "RKLLM_RUN_FINISH", json_object_new_int(2));
    json_object_object_add(llm_call_states, "RKLLM_RUN_ERROR", json_object_new_int(3));
    json_object_object_add(constants, "LLM_CALL_STATES", llm_call_states);

    // RKLLMInputType enum
    json_object* input_types = json_object_new_object();
    json_object_object_add(input_types, "RKLLM_INPUT_PROMPT", json_object_new_int(0));
    json_object_object_add(input_types, "RKLLM_INPUT_TOKEN", json_object_new_int(1));
    json_object_object_add(input_types, "RKLLM_INPUT_EMBED", json_object_new_int(2));
    json_object_object_add(input_types, "RKLLM_INPUT_MULTIMODAL", json_object_new_int(3));
    json_object_object_add(constants, "INPUT_TYPES", input_types);

    // RKLLMInferMode enum
    json_object* infer_modes = json_object_new_object();
    json_object_object_add(infer_modes, "RKLLM_INFER_GENERATE", json_object_new_int(0));
    json_object_object_add(infer_modes, "RKLLM_INFER_GET_LAST_HIDDEN_LAYER", json_object_new_int(1));
    json_object_object_add(infer_modes, "RKLLM_INFER_GET_LOGITS", json_object_new_int(2));
    json_object_object_add(constants, "INFER_MODES", infer_modes);

    // CPU Combinations (computed from masks)
    json_object* cpu_combinations = json_object_new_object();
    json_object_object_add(cpu_combinations, "ALL_CPUS", json_object_new_int(255)); // 0xFF
    json_object_object_add(cpu_combinations, "HIGH_PERF_CPUS", json_object_new_int(240)); // CPU4-7: 0xF0
    json_object_object_add(cpu_combinations, "LOW_POWER_CPUS", json_object_new_int(15)); // CPU0-3: 0x0F
    json_object_object_add(cpu_combinations, "FIRST_TWO_CPUS", json_object_new_int(3)); // CPU0-1: 0x03
    json_object_object_add(cpu_combinations, "LAST_TWO_CPUS", json_object_new_int(192)); // CPU6-7: 0xC0
    json_object_object_add(constants, "CPU_COMBINATIONS", cpu_combinations);
    
    // Comprehensive Metadata
    json_object* metadata = json_object_new_object();
    json_object_object_add(metadata, "generated_from", json_object_new_string("/home/x/Projects/nano/src/external/rkllm/rkllm.h"));
    json_object_object_add(metadata, "defines_found", json_object_new_int(8));
    json_object_object_add(metadata, "functions_found", json_object_new_int(15));
    json_object_object_add(metadata, "enums_found", json_object_new_int(3));
    json_object_object_add(metadata, "structs_found", json_object_new_int(15));
    json_object_object_add(metadata, "generator", json_object_new_string("rkllm_parser_comprehensive"));
    json_object_object_add(metadata, "version", json_object_new_string("1.0"));
    json_object_object_add(constants, "METADATA", metadata);
    
    const char* json_str = json_object_to_json_string(constants);
    *result_json = strdup(json_str);
    json_object_put(constants);
    
    return 0;
}

// Metadata globals
const int g_rkllm_auto_function_count = 15;
const int g_rkllm_auto_define_count = 8;
const int g_rkllm_auto_enum_count = 3;
const int g_rkllm_auto_struct_count = 15;
