#pragma once

/**
 * Auto-generated RKLLM constants and function registry
 * Generated from comprehensive rkllm.h header parsing
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 */

#include <json-c/json.h>

// Comprehensive auto-generated constants function
int rkllm_get_constants_auto(char** result_json);

// Function metadata
extern const int g_rkllm_auto_function_count;
extern const int g_rkllm_auto_define_count;
extern const int g_rkllm_auto_enum_count;
extern const int g_rkllm_auto_struct_count;

